spring:
  application:
    name: coursesystem
  datasource:
    url: jdbc:postgresql://localhost:5432/coursesystem
    username: postgres
    password: ${PG_PASSWORD}
  jpa:
    hibernate.ddl-auto: create
    show-sql: false # Set to true to see generated sql
    properties.hibernate.format_sql: false # Set to true to see how hibernate formats the sql